www/gitlab-ce: disable database migration check for Google::Apis::VERSION 0.50.0
Current package version is using rubygem-google-api-client-0.53.0.
Executing the database migration will show:
```
rake aborted!
NameError: uninitialized constant Google::Apis::VERSION
Did you mean?  VersionCheck
/usr/local/www/gitlab-ce/config/initializers/google_api_client_patch.rb:5:in `<top (required)>'
/usr/local/www/gitlab-ce/config/environment.rb:7:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

I tested it successfully with version 0.53.0.