devel/py-qtbuilder: Fix build
writing byte-compilation script '/tmp/tmp5hwcw4h5.py'
/usr/local/bin/python3.8 /tmp/tmp5hwcw4h5.py
  File "/usr/local/lib/python3.8/site-packages/pyqtbuild/bundle/bundle.py", line 72
    sub_parts = parts[0].split('_')
    ^
SyntaxError: invalid syntax

removing /tmp/tmp5hwcw4h5.py
...
writing list of installed files to '/wrkdirs/usr/ports/devel/py-qtbuilder/work-py38/.PLIST.pymodtmp'
/usr/local/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
  File "/usr/local/lib/python3.8/site-packages/pyqtbuild/bundle/bundle.py", line 72
    sub_parts = parts[0].split('_')
    ^
SyntaxError: invalid syntax

...
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%PYTHON_SITELIBDIR%%/pyqtbuild/bundle/__pycache__/bundle%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Missing: %%PYTHON_SITELIBDIR%%/pyqtbuild/bundle/__pycache__/bundle%%PYTHON_EXT_SUFFIX%%.pyc
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/devel/py-qtbuilder
=>> Error: check-plist failures detected

Approved by:	portmgr (blanket)